/*
*   Copyright (C) {2015}  {Victor Klafke, Charles TheHouse}
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see [http://www.gnu.org/licenses/].
*
*   Contact at: victor.klafke@ecomp.ufsm.br
*/
#pragma once

#define _NN_Get_Skill_Point 1
#define _NN_Weapon_Enchanted 2
#define _NN_Get_Watching_Town_Mission 3
#define _NN_Watching_Town_Success 4
#define _NN_Watching_Town_Awarded 5
#define _NN_Qest06Complete 6
#define _NN_Qest07Complete 7
#define _NN_Qest08Complete 8
#define _NN_Qest09Complete 9
#define _NN_Qest10Complete 10
#define _NN_Qest11Complete 11
#define _NN_Qest12Complete 12
#define _NN_Qest13Complete 13
#define _NN_Qest14Complete 14
#define _NN_Qest15Complete 15
#define _NN_Qest16Complete 16
#define _NN_ServerRebootAfter_1minute 17
#define _NN_Rerun_Game_For_Auto_Patch 18
#define _NN_ServerReboot_After_30Sec 19
#define _NN_ServerReboot_Takes_10min 20
#define _NN_ServerReboot_After_10Sec 21
#define _NN_ServerReboot_Now 22
#define _NN_Bad_Network_Packets 23
#define _NN_Only_Guild_Master_can 24
#define _NN_Champions_Cant_Challange 25
#define _NN_Last_Challange_Cant 26
#define _NN_Allready_Challanged 27
#define _NN_Cant_Get_More_Challanger 28
#define _NN_Need_Sign_Of_Challanger 29
#define _NN_Challanged 30
#define _NN_Cant_Create_More_Summons 31
#define _NN_1_Kind_Summon_in_1_Party 32
#define _NN_Party_Full_Cant_Summon 33
#define _NN_SelectCharacter 34
#define _NN_ServerReboot_Cant_Connect 35
#define _NN_Version_Not_Match_Rerun 36
#define _NN_3_Tims_Wrong_Pass 37
#define _NN_Wait_Checking_Billing 38
#define _DN_Not_Allowed_Account 39
#define _NN_Using_Other_Server_Group 40
#define _NN_Wait_Checking_Billing_t 41
#define _NN_Not_Allowed_Account_t 42
#define _NN_Using_Other_Server_Group_t 43
#define _NN_Cant_Deposit_That_Much 44
#define _NN_Cant_Withdraw_That_Much 45
#define _NN_Newbie_zone 46
#define _NN_Only_Guild_Members 47
#define _NN_Cant_Summon_Dead_Person 48
#define _NN_Summon_Not_Allowed_Here 49
#define _NN_Too_High_Level_To_Summon 50
#define _NN_Not_Enough_Mana 51
#define _SN_Summoned_By_S 52
#define _NN_Level_Up 53
#define _NN_3_Quarters_Bonus 54
#define _NN_2_Quarters_Bonus 55
#define _NN_1_Quarters_Bonus 56
#define _SS_Champion_And_Challanger 57
#define _SN_No_Challanger 58
#define _SN_Winner_Is 59
#define _NN_Teleport_Gate_Requir 60
#define _SN_I_Wwill_Enchant_Your_Weapon 61
#define _NN_Gather_7_Clistals 62
#define _NN_Equip_Weapon_To_Enchant 63
#define _NN_Only_Nomal_Weapons 64
#define _SN_Now_I_Will_Enchant_Your 65
#define _SN_All_Villagers_Thanks_Your 66
#define _NN_Give_You_Some_Reward 67
#define _NN_Guard_This_Village 68
#define _NN_Monster_Attaking_Us_Help 69
#define _NN_Thanks_for_Helping_us 70
#define _NN_Youve_Done_It_Already 71
#define _NN_Cant_Drop_Here 72
#define _NN_Guild_Medal_Cant_Be_Droped 73
#define _NN_Only_To_Equips 74
#define _NN_Cant_Refine_More 75
#define _NN_Fail_To_Refine 76
#define _NN_Fail_To_Level_Up 77
#define _NN_No_Return_Point 78
#define _NN_No_Key 79
#define _NN_Wrong_Trade_Packet1 80
#define _NN_Only_With_Guild_Master 81
#define _NN_Already_Trading 82
#define _NN_Havent_Money_So_Much 83
#define _NN_Opponent_Havent_Money 84
#define _NN_Each_Of_You_Havent_Space 85
#define _NN_You_Have_No_Space_To_Trade 86
#define _NN_Opponent_Have_No_Space_To 87
#define _NN_Wrong_Trade_Packet2 88
#define _NN_Summon 89
#define _NN_Cant_Use_Killed 90
#define _NN_Not_Connected 91
#define _NN_Cant_Use_To_Yourself 92
#define _NN_Cant_Use_To_Killed 93
#define _NN_Only_To_Party_Or_Guild 94
#define _NN_Didnt_Learn_Summon_Skill 95
#define _NN_Cant_Use_That_Here 96
#define _NN_Too_High_Level 97
#define _SN_Summoned_By_S2 98
#define _NN_Relocate 99
#define _SN_S_Relocate_To_You 100
#define _NN_Reply 101
#define _NN_No_One_To_Reply 102
#define _SN_S_is_Connected 103
#define _NN_Only_Guild_Member_Can 104
#define _NN_Maximum_Point_Now 105
#define _NN_Maximum_Point_200_Now 106
#define _NN_Cant_Learn_Other_Class_Skill 107
#define _NN_Not_Enough_Skill_Point 108
#define _NN_Already_Learned_It 109
#define _NN_Need_More_Level_To_Learn 110
#define _NN_Need_More_Mastery_To_Learn 111
#define _NN_Only_Merchant_Sells 112
#define _NN_Not_Enough_Money 113
#define _NN_Only_Guild_Master_Can_Buy_It 114
#define _NN_He_Is_Not_Merchant 115
#define _NN_Only_Merchant_Buy_Yours 116
#define _NN_Dropped_Current_Party_First2 117
#define _NN_Not_Connected2 118
#define _NN_Other_Partys_Member 119
#define _NN_Have_Own_Party_Already 120
#define _NN_Dropped_Current_Party_First 121
#define _NN_Partys_Full 122
#define _DN_Billing_Code 123
#define _DN_Billing_Notice1 124
#define _DD_Billing_Notice2 125
#define _NN_Billing_Notice3 126
#define _NN_Billing_Notice4 127
#define _NN_Billing_Notice5 128
#define _NN_Billing_Notice6 129
#define _NN_Try_Reconnect 130
#define _NN_No_Account_With_That_Name 131
#define _SN_Blocked_Account 132
#define _NN_Wrong_Password 133
#define _NN_Your_Account_From_Others 134
#define _NN_Guild_Battle_Notice1 135
#define _NN_Guild_Battle_Notice2 136
#define _NN_Guild_Battle_Notice3 137
#define _NN_Guild_Battle_Notice4 138
#define _NN_Guild_Battle_Notice5 139
#define _NN_Guild_Battle_Notice6 140
#define _NN_Below_lv20_No_Exp_Loss 141
#define _DN_lose_D_exp 142
#define _NN_In_Arena_No_Exp_Loss 143
#define _NN_Only_Guild_Master_Can 144
#define _NN_Disqualified_By_Guild_Master 145
#define _NN_Disqualify 146
#define _NN_Haven_Guild_Medal 147
#define _NN_Deprivate 148
#define _NN_CarryFull 149
#define _NN_Equip_Particle 150
#define _NN_Purify_Particle 151
#define _NN_Need_1000000_Gold 152
#define _NN_Hurry_Helping_them 153
#define _NN_Party_Only 154
#define _NN_Need_Pure_Divine 155
#define _NN_Initialize_Skill 156
#define _NN_Need_10_Particle 157
#define _NN_Processing_Complete 158
#define _DD_Billing_Notice7 159
#define _DN_Billing_Notice8 160
#define _NN_Disabled_Account 161
#define _NN_No_Guild_Members 162
#define _SN_CastleQuest_Killed 163
#define _NN_CastleQuest_Initialize 164
#define _NN_Deny_Whisper 165
#define _NN_Need_5000000_Gold 166
#define _NN_Cant_Sell_Potion 167
#define _NN_Guild_Tax_0_to_30 168
#define _DD_Set_Guild_Tax 169
#define _NN_CantWhenAutoTrade 170
#define _NN_ItemSold 171
#define _NN_OnlyVillage 172
#define _NN_Only_Named_Guild 173
#define _NN_Only_Once_Per_Day 174
#define _SSD_S_get_S_D 175
#define _NN_Refine_Success 176
#define _DN_Need_D_Sapphire 177
#define _NN_My_King_Bless1 178
#define _NN_My_King_Bless2 179
#define _NN_Need_Level 180
#define _NN_King1_Killed 181
#define _NN_King2_Killed 182
#define _DN_get_D_exp 183
#define _NN_Kingdom 184
#define _NN_King 185
#define _NN_Set_Warp 186
#define _DS_S_Challanged 187
#define _NN_Need_Master 188
#define _DN_Need_D_Sapphire2 189
#define _NN_Need_Guild_Medal 190
#define _NN_Reconnect 191
#define _DN_Need_1000000_For_Challange 192
#define _NN_Battle_In_Progress 193
#define _NN_Battle_Started 194
#define _SS_S_Killed_By_S 195
#define _SS_S_WinBy_S 196
#define _SS_S_S_Draw 197
#define _SSD_S_get_S 198
#define _NN_Leaving_kingdom 199
#define _NN_Next_Chance 200
#define _NN_Congratulations 201
#define _NN_Stat_Initialized 202
#define _DN_Want_Stat_Init 203
#define _DN_D_Cost 204
#define _NN_Cant_with_armor 205
#define _NN_Child_Pay 206
#define _DD_PKPointPlus 207
#define _DD_PKPointMinus 208
#define _DN_CantKillUser 209
#define _SS_War_Declared 210
#define _SS_War_Started 211
#define _SS_War_Canceled 212
#define _NN_War_Stop 213
#define _NN_Cant_Declare_War 214
#define _NN_Party_Level_Limit 215
#define _NN_Summon_Guild 216
#define _NN_Only_Village 217
#define _SN_Your_are_at_war 218
#define _SN_War_to_S 219
#define _SN_War_from_S 220
#define _SS_War_declare_canceled 221
#define _SD_Zakum_Quest_by_S_N 222
#define _NN_Zakum_Quest_empty 223
#define _NN_Only_Level1_Armor 224
#define _NN_Only_Level2_Armor 225
#define _NN_Only_Level3_Armor 226
#define _NN_Only_Level4_Armor 227
#define _NN_Only_By_Water_Scroll 228
#define _NN_Party_Leader_Only 229
#define _NN_NewbieQuest_Already1 230
#define _NN_NewbieQuest_Cheerup1 231
#define _NN_NewbieQuest_Complete1 232
#define _NN_NewbieQuest_Reward1 233
#define _NN_NewbieQuest_Already2 234
#define _NN_NewbieQuest_Cheerup2 235
#define _NN_NewbieQuest_Complete2 236
#define _NN_NewbieQuest_Reward2 237
#define _NN_NewbieQuest_Already3 238
#define _NN_NewbieQuest_Cheerup3 239
#define _NN_NewbieQuest_Complete3 240
#define _NN_NewbieQuest_Reward3 241
#define _NN_NewbieQuest_Already4 242
#define _NN_NewbieQuest_Cheerup4 243
#define _NN_NewbieQuest_Complete4 244
#define _NN_NewbieQuest_Reward4 245
#define _NN_BR_Start1 246
#define _NN_BR_Start2 247
#define _NN_BR_Start3 248
#define _NN_BR_Rewarded 249
#define _NN_BR_Ready1 250
#define _NN_BR_Ready2 251
#define _NN_BR_Ready3 252
#define _NN_INCUBATED 253
#define _NN_Cant_Upgrade_More 254
#define _NN_Mount_Growth 255
#define _NN_Mount_Not_Match 256
#define _NN_Cure_animals 257
#define _DS_S_cure_price_D 258
#define _NN_Cured 259
#define _NN_Cure_failed 260
#define _NN_Incu_Wait_More 261
#define _NN_Incu_Proceed 262
#define _NN_Mount_Level 263
#define _NN_Mount_died 264
#define _NN_3rd_village_limit 265
#define _NN_Only_Sunday 266
#define _NN_Treasure_Map 267
#define _NN_TicketUsed 268
#define _NN_CombineFailed 269
#define _SS_CombineSucceed 270
#define _NN_Wrong_Combination 271
#define _NN_Item_Arrived 272
#define _NN_Cant_get_more_than_2G 273
#define _SN_Learn_Sephera 274
#define _DN_Castle_will_be_open 275
#define _DN_Castle_opened 276
#define _DN_Castle_will_be_closed 277
#define _DN_Castle_closed 278
#define _NN_Only_when_castle_war 279
#define _SN_S_is_charging_castle 280
#define _SN_S_charge_castle 281
#define _NN_Only_same_kingdom 282
#define _SN_Ally_to_S 283
#define _SN_Ally_from_S 284
#define _NN_Ally_Stop 285
#define _SS_Ally_Canceled 286
#define _SS_Ally_Declared 287
#define _NN_Cant_Declare_Ally 289
#define _SSNN_GuildWarResult 290
#define _NN_Need_5_materials 291
#define _NN_snowimp_create_success 292
#define _NN_snowimp_need_2MGold 293
#define _DN_receive_D_gold 294
#define _NN_Someone_is_on_quest 295
#define _NN_Only_at_tor_alter 296
#define _NN_Only_quiz_time 297
#define _NN_Level_limit 298
#define _NN_Message_Sent 299
#define _NN_New_Class_quest 300
#define _NN_New_Class_quest_Lv 301
#define _NN_Set_Soul 302
#define _NN_Soul_Merged 303
#define _NN_Go_to_skill_master 304
#define _NN_Sepherot_created 305
#define _NN_VS_Server 306
#define _NN_NoEmptySlot 307
#define _NN_NewCharacter 308
#define _NN_Soul_n_8_Sephera 309
#define _NN_Congratulations_Trans 310
#define _NN_Need_8_Sephera 311
#define _NN_Cant_in_castle_war 312
#define _NN_SameCharAlready 313
#define _NN_NeedMoreExp 314
#define _NN_BelongToS 315
#define _NN_You_get_the_Apple 316
#define _NN_Already_you_have 317
#define _DD_Correct_answer 318
#define _DD_Incorrect_answer 319
#define _NN_YouNeedTicket 320
#define _NN_Incorrect_kicked 321
#define _NN_Quiz_Cleared 322
#define _NN_Only_By_Quiz_Scroll 323
#define _NN_Only_at_south_of 324
#define _NN_VS_Battle 325
#define _NN_Party_Battle1 326
#define _NN_Party_Battle2 327
#define _NN_Party_Battle3 328
#define _NN_Guild_Battle 329
#define _NN_You_need_feeding_mount 330
#define _NN_Cant_trade_pkmode 331
#define _NN_No_Lotto_Result_Yet 332
#define _NN_Lotto_No_0 333
#define _NN_Lotto_No_1 334
#define _NN_Lotto_No_2 335
#define _NN_Lotto_No_3 336
#define _DN_Lotto_No_4 337
#define _NN_Lotto_No_5 338
#define _NN_FromMonday 339
#define _NN_Level_Limit2 340
#define _DN_LottoResult 341
#define _NN_HitNumber 342
#define _NN_SelectedNumber 343
#define _SD_NoticeLotto 344
#define _NN_CantEatMore 345
#define _NN_SameLevelOnly 346
#define _NN_Need_Elixer 347
#define _NN_Quiz2_Cleared 348
#define _NN_Night_Limited 349
#define _NN_Night_Already 350
#define _NN_Water_Cleared 351
#define _NN_Chat_Prohibition 352
#define _NN_No_Speak 353
#define _NN_Chat_Free 354
#define _DN_Event_Limit 355
#define _NN_Event_Stop 356
#define _NN_Hell_Clear 357
#define _NN_Not_KillBoss 358
#define _NN_Not_Teleport 359
#define _NN_Not_NeedUp 360
#define _NN_Killed_Boss 361
#define _NN_Used_Chao 362
#define _DN_Show_Chao 363
#define _NN_Not_StatInit 364
#define _NN_Another_Server 365
#define _NN_Not_SellItem 366
#define _DD_D_Show_Time 367
#define _DN_Show_Date 368
#define _NN_End_Service 369
#define _NN_Name_Khepra 370
#define _NN_CantGetItem 371
#define _NN_CantAdultUsed 372
#define _DN_Level_Limit 373
#define _NN_Only_when_castle_start 374
#define _NN_Castle_Can_charge 375
#define _NN_Stop_Service 376
#define _DS_Notice_Jackpot 377
#define _SN_End_Khepra 378
#define _NN_Cant_MoveItem 379
#define _NN_Need_ExpMore 380
#define _NN_Need_Trans 381
#define _NN_Need_BeforeQuest 382
#define _DN_Play_Quest 383
#define _NN_NoHave_Quest 384
#define _NN_SND_MESSAGE 385
#define _UN_JACKPOT_MESSAGE 386
#define _NN_NOT_TRANSITEM 387
#define _NN_ITEM_DESTROY 388
#define _SN_Item_BelongToS 389
#define _NN_NotEquip_Saturday 390
#define _DD_Lotto_No_6 391
#define _NN_Need_Kingdom 392
#define _SSDD_HeavenWarResult 393
#define _NN_NeedOverSapp 394
#define _NN_Complete_Quest 395
#define _SSDD_HeavenWarResult2 396
#define _SSDD_HeavenWarResult3 397
#define _NN_GAMEROOM_ITEM 398
#define _NN_PLUS_POINT 399
#define _DN_PLUS_CPPOINT 400
#define _DN_SUB_CPPOINT 401
#define _NN_Only_OneSkillLearn 402
#define _NN_Befor_LearnSkill 403
#define _NN_Cash_ChargeOk 404
#define _NN_Cash_ChargeErr 405
#define _NN_NOTUSE_TRANS 406
#define _NN_NOTUSE_YET 407
#define _NN_Maximum_Point_255_Now 408
#define _NN_EquipArmor_Refine 409
#define _DN_Recovery_Life 410
#define _DN_CanUse_Time 411
#define _NN_Crack_Block 412
#define _SN_Use_Item 413
#define _I64D_TOWN_TAX 414
#define _DD_QUIZ 415
#define _DD_NOT_QUIZ 416
#define _NN_GIVE_TOWN_TAX 417
#define _NN_CANT_USE_NIGHTMARE 418
#define _NN_CHANGE_PASSWORD 419
#define _DN_CHANGE_COUNT 420
#define _SN_CREATEGUILD 421
#define _SN_JOINGUILD 422
#define _DN_TOWNSPEOPLE 423
#define _DN_BASEWORRESULT 424
#define _DN_BASEWORSTART 425
#define _DD_SERVERWAR 426
#define _DD_JOINTOWNPEP 427
#define _DN_DOSERVERWAR 428
#define _NN_GSTRING_ERR 429
#define _NN_CANT_USE_ID 430
#define _NN_OPEN_HELLGATE 431
#define _DN_TOWNBOUNS 432
#define _DD_KINGDOMWAR_START 433
#define _DD_KINGDOMWAR_END 434
#define _NN_Check_User_Info 435
#define _NN_LockSetMessage 436
#define _NN_CanelMessage 437
#define _NN_LockCheckMessage 438
#define _NN_LockPsSetMessage 439
#define _NN_LockPsChangeMessage 440
#define _DN_ServerWarTo 441
#define _DN_ServerWarFrom 442
#define _NN_LockPsWrongPassMessage 443
#define _ND_GenDarkShadow 444
#define _NN_Refine_Down 445
#define _NN_CantCreateGOD2 446
#define _NN_CantUseIt 447
#define _NN_AlreadyClosing 448
#define _NN_NotMatchMission 449
#define _NN_ClearMission 450
#define _NN_NOT_TRANS3ITEM 451
#define _NN_FUll_CARRY 452
#define _NN_APPLY_EVENT 453
#define _NN_CANT_APPLY_EVENT 454
#define _NN_KINGDOM_BLUE 455
#define _NN_KINGDOM_RED 456
#define _NN_SWAR_AHEAD 457
#define _NN_SWAR_TRUCE 458
#define _NN_GIVEUP_SERVERWAR 459
#define _ND_SERVERCLAN 460
#define _NN_Charm_Stone 461
#define _SS_Combin_12Succ 462
#define _SS_Guild_to_drop 463
#define _NN_PARTY_TEL 464
#define _DN_LIMITWARNING 465
#define _DN_LIMITTIME 466
#define _DN_GUILDMESSAGE 467
#define _DN_CHARSELECTMESSAGE 468
#define _NN_WAITFORDELCHAR 469
#define _NN_WAITFORLOGIN 470
#define _NN_PASSWORDERROR 471
#define _NN_ISNOTALLOWEDACCOUNT 472
#define _NS_GETEXP 473
#define _NN_GETJEWALITEM 474
#define _SS_PLUSMILEAGEPOINT 475
#define _NN_FAILURE 476
#define _SN_WANTEQUIPITEM 477
#define _SN_Item_Arrived 478
#define _DN_Mileage_Point 479
#define _DN_BeforLearnSkill 480
#define _SN_Learn_Skill 481
#define _NN_Maximum_Point_320_Now 482
#define _NN_NOT_SUBJECT_TO_EVENT 483
#define _DN_LIMITDURING_3HOUR 484
#define _NN_LIMITDURING_OVER 485
#define _SN_AUCTION_START 486
#define _NN_AUCTION_END 487
#define _DS_AUCTION_PERIOD 488
#define _SSD_AUCTION_SUC 489
#define _SN_AUCTION_BID 490
#define _NN_AUCTION_PLACE 491
#define _NN_NEWBIEEVENTSERVER 492
#define _NN_LIMIT_FAME 493
#define _SN_APPEAR_MOB 494
#define _SN_JOINRESTRICTED 495
#define _SD_RAID_BONUS 496
#define _DD_KILLSCORE 497
#define _NN_GOD2CHARONLY_ 498
#define _NN_MOREKILLPOINT 499
#define _DD_KINGDOMWAR_BEGIN 500
#define _DN_CHANNELWAR_BEGIN 501
#define _NN_CHANNELWAR_ZONE 502
#define _SN_GUILDZONE_NPC_1_ 503
#define _SN_GUILDZONE_NPC_2_ 504
#define _SN_CHANNELWAR_DROP_ 505
#define _SN_KINGDOMWAR_DROP_ 506
#define _DN_NO_TOWNSPEOPLE 513
#define _DN_ANOTHER_TOWNSPEOPLE 514
#define _DN_WAR_JOIN_TOWNSPEOPLE 515
#define _DN_TOWN_SOUL_BUFF 516
#define _DN_TOWN_SOUL_NOBUFF 517
#define _DN_TOWN_SORRY 518
#define _SN_BRINGITEM 519
#define _DN_SANCREQ 520
#define _DN_NeedDonate 521
#define _NN_MAC_Block 522
#define _DN_NEEDFAME 523
#define _SN_NEEDCLASS 524
#define _NN_MAX_ACCOUNTMAC 525
#define _NN_ONLYTRADE 526
#define _NN_NOSTOCK 527
#define _SN_BOXSTATE 528
#define	_NN_PINCODE_INVALID	529
#define _NN_PINCODE_3TIMES 530
#define _NN_MAX_BAG 531
#define _DD_NightmareTime 532
#define _DN_REMAINDONATE 533
#define _SN_CARBUNCLEMSG 534
#define _NN_GUILDCREATECLAN 535
#define _SS_BASEWORKILLTOWER 536
#define _NN_ENCAMPMENTBORN 537